export const FETCH_QUESTIONARE_TITLES = 'FETCH_QUESTIONARE_TITLES'
export const FETCH_QUESTIONARE_TITLES_ERROR = 'FETCH_QUESTIONARE_TITLES_ERROR'
export const FETCH_TEST_ID = 'FETCH_TEST_ID'

export const FETCH_ACTIVE_QUESTIONARE_TITLE_AND_QUESTIONS = 'FETCH_ACTIVE_QUESTIONARE_TITLE_AND_QUESTIONS'
export const RETRY_HANDLER = 'RETRY_HANDLER'
export const REPEAT_HANDLER = 'REPEAT_HANDLER'
export const ANSWER = 'ANSWER'

export const IS_QUESTIONNAIRE_FINISHED = 'IS_QUESTIONNAIRE_FINISHED'
export const NEXT_QUESTION = 'NEXT_QUESTION'